name: elgam3a
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_icons: ^1.0.0
  selection_picker: ^0.1.0
  kf_drawer: ^1.1.2
  rflutter_alert: ^1.1.0
  flrx_validator: ^0.4.0+2
  image_picker: ^0.6.7+14
  font_awesome_flutter: ^8.10.0
  flutter_svg: ^0.19.2+1
  provider: ^4.3.2+3
  loading_indicator: ^1.2.0
  persistent_bottom_nav_bar: ^3.1.0
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_analytics: ^6.2.0
  firebase_performance: ^0.4.2
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/


  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri/Calibri-Light.ttf
          weight: 300
        - asset: assets/fonts/Calibri/Calibri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Calibri/Calibri-Bold.ttf
          weight: 700